### PR TITLE
Matgl Version Update

### PR DESCRIPTION
**Pull request by melo-gonzo**
Updating M3GNet example to show extra steps needed when gpu training is requested. Bumping matgl to latest version. Updating internal matgl calls to comply with updated matgl API.

### CODE REVIEW

**Review by laserkelvin — APPROVED** [review]
LGTM

**Comment by laserkelvin** [comment]
Before we merge this, let's see if the latest conversation in #92 can be addressed by these examples as well.

**Comment by melo-gonzo** [comment]
This needs some refinement actually. I am seeing the generator issues mentioned in #92, not sure why I didn't run into that before - may have had an outdated package installed when testing. I'll continue to take a look at this.

**Comment by melo-gonzo** [comment]
I'm going to revert the changes in the example script for now, since there is not definitive solution to getting training working with multi-gpu and num_workers>0 _yet_. I think we can merge in the PR with the other changes since it'll be a required update, regardless of how the other issue is sorted out. If that sounds good @laserkelvin let me know.

**Comment by melo-gonzo** [comment]
`matgl` merged in changes ([matgl#215](https://github.com/materialsvirtuallab/matgl/pull/215)) and released version `0.9.2` which solve issues seen in #105. This API update in matsciml ensures compatibility with matgl's latest version.

**Pull request merged**
